name: CI - Integration Test 


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        python-version: [3.9]

    steps:
    - name: Git checkout 
      uses: actions/checkout@v2

    - name: Install Node JS ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Newman dependency
      run: npm install -g newman

    - name: Run the API and Postman's tests
      run: |
        python main.py &
        sleep 2
        cd test/ && newman run api.postman_collection.json -e api.postman_environment.json
        kill -9 `lsof -i:5000 -t`
      env:
        FLASK_ENV: development

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: tech-challenge

